### ISSUE TITLE
Can't find the license

### ISSUE THREAD

**Issue by pranasblk** [gramoli/synchrobench#27]
Would you mind adding one?

Thanks!

**Comment by gramoli** [comment]
There are two versions subject to different licences: 
- the licence for the C/C++ version can be found at:
https://github.com/gramoli/synchrobench/blob/master/c-cpp/COPYING
- the licence for the Java version can be found at: 
https://github.com/gramoli/synchrobench/blob/master/java/COPYRIGHT
