### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by JMMackenzie** [gramoli/synchrobench#3]
I found that in order to compile this library, I had to do:

    cd ~/foo/bar/synchrobench/c-cpp/src/utils/
    rm -rf estm-0.3.0
    wget http://www.it.usyd.edu.au/~gramoli/tmp/doc/sw/estm-0.3.0.tgz
    tar xzvf estm-0.3.0.tgz
    cd ~/foo/bar/synchrobench/c-cpp
    make

It appears that the issue was that in the estm-0.3.0/lib/ the file libst.a is empty.

**Comment by gramoli** [comment]
Thank you, the two bugs you mentioned should be fixed by now.

Vincent

________________________________
