### ISSUE TITLE
libnuma: Warning: Cannot read node cpumask from sysfs

### ISSUE THREAD

**Issue by sgauatm** [gramoli/synchrobench#35]
Trying to run lockfree-numask-skiplist, but it throws segmentation fault with libnuma warning.
"libnuma: Warning: Cannot read node cpumask from sysfs
Segmentation fault (core dumped)"

**Comment by chenfengkg** [comment]
> Trying to run lockfree-numask-skiplist, but it throws segmentation fault with libnuma warning.
> "libnuma: Warning: Cannot read node cpumask from sysfs
> Segmentation fault (core dumped)"

Can you share how did you solve this problem？

**Comment by tsalemy** [comment]
Attached a fix.... libnuma error might create a false positive error in the eyes of the programmer. The true segmentation fault happens in the adjusted block of code. https://github.com/gramoli/synchrobench/pull/36
