### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by JMMackenzie** [gramoli/synchrobench#4]
The link(s) in the readme at: https://github.com/gramoli/synchrobench/tree/master/c-cpp/src/utils/estm-0.3.0
seems to be broken. I think it's the redirect from the link however. 

http://lpd.epfl.ch/gramoli/php/estm.php redirects to http://sydney.edu.au/engineering/it/~gramoli/estm.php but should redirect to http://sydney.edu.au/engineering/it/~gramoli/php/estm.php

**Comment by gramoli** [comment]
Both redirect to the proper Web page now.
