### ISSUE TITLE
compilation with java 7

### ISSUE THREAD

**Issue by remisharrock** [gramoli/synchrobench#5]
if you compile with java 7 you get these errors:
[javac] synchrobench-master/java/src/arrays/lockbased/Vector.java:40: error: cannot find symbol
[javac] import java.util.Spliterator;
[javac] ^
[javac] symbol: class Spliterator
[javac] location: package java.util

For files
java/src/arrays/lockbased/Vector.java
java/src/arrays/sequential/SequentialVector.java
java/src/arrays/transactional/Vector.java

**Comment by gramoli** [comment]
Yes, Java 8 breaks backward compatibility by defining SplitIterator in interfaces:
http://stackoverflow.com/questions/26480213/java-8-spliterator-iterator-collection-and-default-implemenations-in-interf

As I have recently added to the 'Java version' section of https://github.com/gramoli/synchrobench/blob/master/java/INSTALL, I would recommend:
- either to remove the only Java8-specific data structure (that uses the new Java-8 StampLock): src/linkedlists/lockbased/{NodeStampLock.java, VersionedListSetStampLock.java} and to compile Synchrobench with Java 7.
- or to move to Java 8 (but at this stage, I cannot guarantee that the transactional data structures can be supported for the same backward compatibility issue as above).

**Comment by gramoli** [comment]
No need to remove files anymore to compile with Java 6 to 8. Depending on the Java version the incompatible files that require the StampLock will not be compiled.
