### ISSUE TITLE
package not correct for 4 files

### ISSUE THREAD

**Issue by remisharrock** [gramoli/synchrobench#6]
Files
java/src/linkedlists/lockfree/NodeBase.java
java/src/linkedlists/lockfree/NodeLinked.java
java/src/linkedlists/lockfree/NodeMarked.java
java/src/linkedlists/lockfree/NonBlockingLinkedListSetRTTI.java

are not in the good package

**Comment by gramoli** [comment]
Thanks, I have just renamed their packages.

**Comment by alivaramesh** [comment]
You have forgotten to rename the package name for java/src/linkedlists/lockfree/NodeLinked.java!

**Comment by gramoli** [comment]
Thanks, should be fixed now.
