### ISSUE TITLE
Encoding a data structure

### ISSUE THREAD

**Issue by singam-sanjay** [gramoli/synchrobench#7]
I understand that synchrobench simulates an environment around a concurrent data structure to evaluate its performance with regard to its synchronisation techniques.

How is the data structure encoded and given to synchrobench ?

(I'm more interested in the C/C++ part)

Thank You

**Comment by gramoli** [comment]
Hi Singapuram,
Synchrobench Java uses reflection for the user to specify a data structure on the command line as a parameter of the main class that will dynamically test it.

However, all inidividual data structures of Synchrobench C/C++ are compiled into separate binaries as explained at https://sites.google.com/site/synchrobench/c-c-version

I hope this clarifies your doubts and let me know if you have further questions,

Thank you,

Vincent

**Comment by singam-sanjay** [comment]
@gramoli Thank You !
